# Generated by Django 5.1.6 on 2025-03-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='usuario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='categoria',
            field=models.CharField(choices=[('Entretenimiento', 'Entretenimiento'), ('Música', 'Música'), ('Educación', 'Educación'), ('Otros', 'Otros')], max_length=20),
        ),
    ]
