# Generated by Django 5.1.6 on 2025-03-18 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_suscripcion_usuario_alter_suscripcion_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='categoria',
            field=models.CharField(choices=[('Entretenimiento', 'Entretenimiento'), ('Música', 'Música'), ('Educación', 'Educación'), ('Otros', 'Otros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
