# Generated by Django 5.1.6 on 2025-03-19 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_suscripcion_categoria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suscripcion',
        ),
    ]
